export const productos = [
  {
    code: "EZ-00023",
    image: "producto",
    title: "Tender vertical 3 niveles",
    dolarCost: "23.9",
    description: "El tender de ropa vertical plegable de 3 niveles es una solución práctica para el secado de prendas en espacios reducidos. Sus dimensiones son 170cm de altura y 65 cm de ancho. Fabricado con caños de acero y plástico, cuenta con una pintura inoxidable que garantiza su durabilidad. Dispone de ruedas reforzadas para facilitar su movilidad, y su diseño plegable permite un almacenamiento sencillo. Además, incluye perchas plegables y ganchos para ropa interior, optimizando el espacio de secado.",
    destacado: true,
  },
  {
    code: "EZ-00030",
    image: "producto",
    title: "Tender vertical 4 niveles",
    dolarCost: "26.04",
    description: "Tender de ropa vertical plegable de 4 niveles, con altura de 170cm y ancho de 75cm. Diseño plegable para fácil guardado. Estructura resistente al viento y fabricada en acero inoxidable, lo que asegura durabilidad y resistencia a la corrosión. Incluye ruedas antideslizantes para un desplazamiento seguro. Color azul.",
    destacado: true,
  },
  {
    code: "JJE-135002",
    image: "producto",
    title: "Secaplatos 85cm",
    dolarCost: "25.68",
    description: "Secaplatos escurridor de aluminio premium de 85cm de largo, 34cm de ancho y 52cm de alto. Cuenta con dos niveles, capacidad para 12 platos, soporte para cubiertos y secavasos. Diseño resistente y fácil de ensamblar, ideal para optimizar el espacio en la cocina.",
    destacado: true,
  },
  {
    code: "JJE-135001",
    image: "producto",
    title: "Secaplatos 65cm",
    dolarCost: "21.46",
    description: " Secaplatos escurridor de aluminio premium de 65cm de largo, 34cm de ancho y 52cm de alto. Cuenta con dos niveles, capacidad para 12 platos, soporte para cubiertos y secavasos. Diseño resistente y fácil de ensamblar, ideal para optimizar el espacio en la cocina.",
    destacado: true,
  },
  {
    code: "EZ-00010",
    image: "producto",
    title: "Bomba dispenser",
    dolarCost: "2.32",
    description: "La bomba dispensadora de agua recargable por USB es una solución práctica para extraer agua de bidones de hasta 20 litros. Sus dimensiones son 13cm de altura y 7cm de diámetro. Cuenta con una batería recargable mediante USB, similar a un teléfono móvil, con una duración aproximada para dispensar hasta 6 bidones de 20 litros por carga. El dispositivo es compatible con bidones de diversas capacidades, desde 4 hasta 20 litros. Incluye un tubo de acero, una manguera de entrada y un cable de carga USB.",
    destacado: true,
  },
  {
    code: "EZ-000013",
    image: "producto",
    title: "Flambeador",
    dolarCost: "2.76",
    description: " El soplete flambeador gastronómico recargable es una herramienta esencial para la cocina y la repostería.Fabricado en aluminio resistente, cuenta con una llama ajustable que alcanza hasta 1.300°C, permitiendo diversas aplicaciones culinarias como flambeado, gratinado y caramelizado. Sus dimensiones son 13,5cm de alto, 10cm de largo y 5,2cm de diámetro en la base, con un peso de 115 gramos, lo que facilita su manipulación. Dispone de encendido electrónico y es recargable con gas butano (no incluido).",
    destacado: true,
  },
  {
    code: "EZ-00008",
    image: "producto",
    title: "Deterctor de humo",
    dolarCost: "2.06",
    description: "El sensor detector de humo autónomo es un dispositivo esencial para la seguridad en hogares, oficinas y cocheras. Detecta la presencia de humo en el aire y emite una alarma sonora de 85dB, alertando sobre posibles incendios o intoxicaciones. Se recomienda instalarlo en el techo, preferiblemente en el centro de la habitación, para una detección óptima. El dispositivo es inalámbrico y funciona con una batería de 9V (no incluida). Está fabricado en plástico resistente y cubre una distancia de hasta 20 metros. Sus dimensiones son 10,5cm de altura.",
  },
  {
    code: "EZ-3005",
    image: "producto",
    title: "Secaplatos modelo S",
    dolarCost: "8.58",
    description: "Escurridor de platos cromado de 2 niveles, con capacidad para 14 platos. Incluye soporte para cubiertos y secavasos desmontables. Dimensiones: 35cm de ancho, 25cm de profundidad y 37cm de altura. Bandeja plástica desmontable para facilitar el drenaje. Ideal para optimizar el espacio en la cocina.",
  },
  {
    code: "EZ-00007",
    image: "producto",
    title: "Cubrezapatillas",
    dolarCost: "2.5",
    description: "El cubre zapatillas de silicona impermeable es un accesorio diseñado para proteger el calzado de la lluvia, barro y nieve. Fabricado con silicona de alta calidad, es 100% impermeable y a prueba de fugas, garantizando que tus zapatos permanezcan secos y limpios. Su suela antideslizante proporciona seguridad al caminar en superficies mojadas. Disponible en talles S (números 29-34), M (35-39) y L (40-44), se adapta a la mayoría de los tamaños de calzado estándar. Estas fundas son reutilizables, fáciles de limpiar y su diseño elástico permite un ajuste cómodo y seguro.",
  },
  {
    code: "JJE-125001",
    image: "producto",
    title: "Carro chango",
    dolarCost: "27.64",
    description: "Changuito de compras plegable y reforzado, con estructura de aluminio ultraliviana y bolsa de poliéster resistente. Soporta hasta 35kg de carga y cuenta con ruedas grandes para facilitar el transporte. Incluye manija ajustable y es ideal para subir escaleras. Diseño compacto y fácil de almacenar.",
  },
  {
    code: "DUCHA-C",
    image: "producto",
    title: "Ducha cuadrada 20X20cm",
    dolarCost: "2",
    description: "Flor de ducha cuadrada de 20x20cm, fabricada en acero inoxidable con boquillas de silicona anticalcáreas. Diseño ultrafino que proporciona un efecto de lluvia uniforme. Incluye rótula ajustable para orientar el flujo de agua. Conexión estándar de 1/2 pulgada, compatible con la mayoría de los sistemas de ducha. No incluye brazo de ducha.",
  },
  {
    code: "JJE-10011",
    image: "producto",
    title: "Zorra 130kg",
    dolarCost: "51.24",
    description: "Carro plegable de aluminio reforzado, soporta hasta 130kg. Dimensiones: 115cm de alto, 50cm de ancho y 51cm de profundidad; plegado mide 88cm de alto. Ruedas de plástico de 16x3cm y mango expandible con puños ergonómicos de 10x3cm. Ideal para transportar cargas pesadas en diversas superficies.",
  },
  {
    code: "NEJ-160",
    image: "producto",
    title: "Tender 160cm blanco",
    dolarCost: "12.54",
    description: "Tender plegable con alas, dimensiones 160cm de largo, 50cm de ancho y 95cm de alto. Varillas antideslizantes reforzadas de metal. Estructura de acero inoxidable con pintura anticorrosiva. Diseño plegable para fácil almacenamiento. Ideal para secar ropa en espacios reducidos.",
  },
  {
    code: "NEJ-180",
    image: "producto",
    title: "TENDER 180cm blanco",
    dolarCost: "13.43",
    description: "Tender plegable con alas, dimensiones 180cm de largo, 50cm de ancho y 105cm de alto. Varillas antideslizantes reforzadas de metal. Estructura de acero inoxidable con pintura anticorrosiva. Diseño plegable para fácil almacenamiento. Ideal para secar ropa en espacios reducidos.",
  },
  {
    code: "SHIR-160",
    image: "producto",
    title: "Tender 160cm gris",
    dolarCost: "14.63",
    description: "Tender plegable con alas, dimensiones 160cm de largo, 50cm de ancho y 95cm de alto. Varillas antideslizantes reforzadas de metal. Estructura de acero inoxidable con pintura anticorrosiva. Diseño plegable para fácil almacenamiento. Ideal para secar ropa en espacios reducidos.",
  },
  {
    code: "EZ-000017",
    image: "producto",
    title: "Luz led bicicleta (par)",
    dolarCost: "2.4",
    description: "Kit de luces LED para bicicleta, incluye luz delantera blanca y luz trasera roja, ambas recargables por USB. Cada luz ofrece 7 modos de iluminación, incluyendo luz fija e intermitente. Resistentes a salpicaduras de agua, no sumergibles. Dimensiones: 7,5cm de ancho x 2cm de alto. Incluye arandelas de silicona para adaptarse a tubos de asiento de 12 a 32mm. Ideal para mejorar la visibilidad y seguridad en ciclismo.",
  },
  {
    code: "JJE-135007",
    image: "producto",
    title: "Secaplato",
    dolarCost: "18.97",
    description: "Secaplatos de 3 niveles con capacidad para 16 platos, fabricado en acero inoxidable. Incluye bandeja y cubiertero de plástico desmontables. Dimensiones: 55cm de largo, 25cm de ancho y 45cm de alto. Ideal para organizar y secar vajilla en la cocina.",
  },
  {
    code: "JJE-135005",
    image: "producto",
    title: "Secaplato",
    dolarCost: "31.54",
    description: "Secaplatos de acero inoxidable de 3 niveles, con capacidad para 14  platos. Incluye cubiertero y secavasos. Dimensiones: 46cm de largo, 26cm de ancho y 45cm de alto. Diseño moderno y fácil de limpiar, ideal para mantener la cocina organizada.",
  },
  {
    code: "EZ-000024",
    image: "producto",
    title: "Termometro de cocina",
    dolarCost: "1.5",
    description: "Termómetro digital de cocina con sonda de acero inoxidable, rango de medición de -50°C a 300°C, precisión de ±1°C, pantalla LCD retroiluminada, función de apagado automático tras 10 minutos, y botón para cambiar entre °C y °F. Incluye funda protectora y batería AG13. Ideal para medir la temperatura de carnes, líquidos y preparaciones de repostería.",
  },
  {
    code: "ez-",
    image: "producto",
    title: "Balanza",
    dolarCost: "2.3",
    description: "Balanza digital de cocina SF-400 con capacidad máxima de 10kg, sensibilidad de 1g, función tara, apagado automático, indicador de sobrepeso, base antideslizante y funcionamiento con 2 pilas AA (no incluidas). Dimensiones: 24cm x 16,5cm. Ideal para recetas y control de porciones.",
  }
];